language: ruby
script: 'ci/travis.rb'
before_install:
env:
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
rvm:
  - 2.1
matrix:
  fast_finish: true
notifications:
  email: false
cache: bundler
bundler_args: --path vendor/bundle --without test --jobs=3 --retry=3
services:
  - memcached
  - postgresql
  - mysql
  - redis
  - rabbitmq
addons:
  postgresql: "9.3"
