script: 'ci/travis.rb'
before_install:
rvm:
  - 2.0.0
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,as,av"
  - "GEM=ar:mysql"
  - "GEM=ar:mysql2"
  - "GEM=ar:sqlite3"
  - "GEM=ar:postgresql"
matrix:
  fast_finish: true
notifications:
  email: false
bundler_args: --path vendor/bundle --without test --jobs=3 --retry=3
services:
  - memcached
  - postgresql
  - mysql
